export const MODAL_BODY_TYPES = {
  USER_DETAIL: "USER_DETAIL",
  DECREE_ADD_NEW: "DECREE_ADD_NEW",
  DECREE_EDIT: "DECREE_EDIT",
  ARTICLE_ADD_NEW: "ARTICLE_ADD_NEW",
  ARTICLE_EDIT: "ARTICLE_EDIT",
  CLAUSE_ADD_NEW: "CLAUSE_ADD_NEW",
  CLAUSE_EDIT: "CLAUSE_EDIT",
  FINE_ADD_NEW: "FINE_ADD_NEW",
  FINE_EDIT: "FINE_EDIT",
  FINE_TYPE_ADD_NEW: "FINE_TYPE_ADD_NEW",
  FINE_TYPE_EDIT: "FINE_TYPE_EDIT",
  SIGN_ADD_NEW: "SIGN_ADD_NEW",
  SIGN_EDIT: "SIGN_EDIT",
  SIGN_TYPE_ADD_NEW: "SIGN_TYPE_ADD_NEW",
  SIGN_TYPE_EDIT: "SIGN_TYPE_EDIT",
  QUESTION_ADD_NEW: "QUESTION_ADD_NEW",
  QUESTION_EDIT: "QUESTION_EDIT",
  NEW_ADD_NEW: "NEW_ADD_NEW",
  NEW_EDIT: "NEW_EDIT",
  CONFIRMATION: "CONFIRMATION",
  DEFAULT: "",
};

export const RIGHT_DRAWER_TYPES = {
  NOTIFICATION: "NOTIFICATION",
  CALENDAR_EVENTS: "CALENDAR_EVENTS",
};

export const CONFIRMATION_MODAL_CLOSE_TYPES = {
  DECREE_DELETE: "DECREE_DELETE",
  ARTICLE_DELETE: "ARTICLE_DELETE",
  CLAUSE_DELETE: "CLAUSE_DELETE",
  FINE_DELETE: "FINE_DELETE",
  FINE_TYPE_DELETE: "FINE_TYPE_DELETE",
  SIGN_DELETE: "SIGN_DELETE",
  SIGN_TYPE_DELETE: "SIGN_TYPE_DELETE",
  QUESTION_DELETE: "QUESTION_DELETE",
  NEW_DELETE: "NEW_DELETE",
};
