export const MODAL_BODY_TYPES = {
  USER_DETAIL: "USER_DETAIL",
  DECREE_ADD_NEW: "DECREE_ADD_NEW",
  DECREE_EDIT: "DECREE_EDIT",
  ARTICLE_ADD_NEW: "ARTICLE_ADD_NEW",
  ARTICLE_EDIT: "ARTICLE_EDIT",
  QUESTION_ADD_NEW: "QUESTION_ADD_NEW",
  QUESTION_EDIT: "QUESTION_EDIT",
  NEW_ADD_NEW: "NEW_ADD_NEW",
  CONFIRMATION: "CONFIRMATION",
  DEFAULT: "",
};

export const RIGHT_DRAWER_TYPES = {
  NOTIFICATION: "NOTIFICATION",
  CALENDAR_EVENTS: "CALENDAR_EVENTS",
};

export const CONFIRMATION_MODAL_CLOSE_TYPES = {
  DECREE_DELETE: "LEAD_DELETE",
};
